### ISSUE TITLE
V1.3.5 crash on start

### ISSUE THREAD

**Issue by billie80** [Baltasarq/nadamillas#16]
Just installed the new version but unfortunately it immediately crashes.
Maybe a database problem introduced with the addition of the new fields.

**Comment by Baltasarq** [comment]
Sigh... oh dear... I thought I'd double-checked this. Okay, I've published a new version. Hope it now works.

**Comment by billie80** [comment]
Thanks! The new version V1.3.6 now starts but it crashes when I try to add a new entry and when I try to open the settings.

**Comment by Baltasarq** [comment]
**What??** That's totally unexpected...

Okay, I need to know...

1. Your version of Android, to test the app in this specific version (Settings >> Phone info).
2. Are you using the APK or upgrading through Google Play?
3. What happens when you go to the "history" option on the main menu of the main screen. Can you see the listing of your previous workouts?

Sorry of the inconvenience.

**Comment by billie80** [comment]
No problem!
1. I am still on Android 10
2. I use the APK over the IzzyOnDroid Repository
3. Accessing the history works well. I can access everything but the settings and when trying to add a new entry.

**Comment by Baltasarq** [comment]
Fine, since you can access the history, note that you do also have access to edit a workout and to add a new one from there. What happens when you tap on the "+" button at the bottom? What happens when you try to modify a workout?

**Comment by billie80** [comment]
When trying to edit a workout it crashes. I don't see an option to add new workouts from the history. From the main screen it crashes when trying to add a workout using the + on bottom right as well as from the hamburger menu top left and the three dots top right.

**Comment by Baltasarq** [comment]
I've been working on this.

I've run nadamillas in an Android 10 emulator. As I feared, no bug showed up. From this point, I can only make assumptions (some corner case state of the db?), and patching with code developed blindly is... a recipe for disaster.

There are a couple of things you could do:

1. Uninstall the app and reinstall it. The problem is, you would lose all your data. Don't I suppose you made a backup through Settings >> Export before all of this? If so, then you can uninstall completely the app and restore the database through Settings >> Import.
2. Capture a bug report for me. You should follow the [instructions in the android developers documentation pages for capturing bug reports](https://developer.android.com/studio/debug/bug-report), but anyway it means you'll have to set your phone in developer mode (you can deactivate it later). Then, you would start the app and make it crash, and then you would capture a bug report and send it to me.

**Comment by billie80** [comment]
1. Believe it or not I am one of those who have regular backups so fortunately no data is lost.
2. Sure I can create a bug report. Where can I send it privately?

**Comment by MopsTMC** [comment]
I have the same effects after the update on Android 14 (OneUI 6.0). The Notes section also does not appear anymore on past workouts when browsing the calendar, not sure if its data is gone completely. Could trying to parse it be a cause of crash?

**Comment by Baltasarq** [comment]
> I have the same effects after the update on Android 14 (OneUI 6.0). The Notes section also does not appear anymore on past workouts when browsing the calendar, not sure if its data is gone completely. Could trying to parse it be a cause of crash?

I don't really know. Do you have a backup of your data? If you have, then import it replacing the current sessions. This should stabilize the db. Or can't you access settings neither?

**Comment by Baltasarq** [comment]
> 1. Believe it or not I am one of those who have regular backups so fortunately no data is lost.
Good on you!!
 
>     2. Sure I can create a bug report. Where can I send it privately?
To: baltasarq at gmail.com

**Comment by MopsTMC** [comment]
> I don't really know. Do you have a backup of your data? If you have, then import it replacing the current sessions. This should stabilize the db. Or can't you access settings neither?

I can neither access settings (without having to clear app data) nor do I have a backup, unfortunately

**Comment by Baltasarq** [comment]
Okay, bear with me both. Thanks.

**Comment by Baltasarq** [comment]
Found it! Though It was on Settings (this is a preferences object, no database involved).

Though I have no clue of how the stray value causing the bug happened.
Anyway, I've released a new APK. Can you both test it?

**Comment by billie80** [comment]
V1.3.7 now works as expected. Thank you very much for taking care of this so quickly. Now I can go swimming again. 😀
¡Muchas gracias!

**Comment by MopsTMC** [comment]
Works for me too, thanks!

**Comment by Baltasarq** [comment]
> Works for me too, thanks!

Great! Thanks.
