### ISSUE TITLE
+ button hide delete button if there more than 2 activity i a day

### ISSUE THREAD

**Issue by muhammadarif1** [Baltasarq/nadamillas#3]
#### EXPECTED BEHAVIOR 
users should be able to delete notes to two or more without obstructing the add button
#### ACTUAL BEHAVIOR
when the user wants to delete the second or third note, the + button blocks the delete button
#### STEP TO REPRODUCE
- open the app
- create more than 2 note i a same date
then go into the application calendar then go to the date that you made a note and try to delete the second record and see if the + button blocks the delete button
#### BUG RECORDING
![Screenshot_2019-05-26-05-37-47-98](https://user-images.githubusercontent.com/36690337/58375264-eff31880-7f78-11e9-9cc2-b3106efdb43e.png)

**Comment by Baltasarq** [comment]
This is (hopefully) solved now.

I've also modified the options available by hiding them in a dialog. So, you first choose the options button in the entry, and then choose the option you want from the dialog.

The advantages here are twofold: first and foremost, gives more room on screen real state, and also makes it possible to add more options in the future, if necessary, without changing the code too much.
In order to be able to use a dialog with icons, I had to bump the minimum Android version to 21 (Android 5.0). This should not be a problem, since the Google Play statistics page shows that there are no devices under 5.0.
